### ISSUE TITLE
[Feature] Analytics!

### ISSUE THREAD

**Issue by ItaloSa** [ufrpe-devs/ufrpe-devs.github.io#22]
## Opa, qual a bronca?

Temos um belo site, certo? Mas aí não sabemos se ele está sendo útil. O motivo? Não temos dados! Isso mesmo, não temos nenhuma feedback de visitas. 

O que precisamos é configurar o Google Analytics. Não precisamos, no momento de muitos detalhes. Precisamos das informações básicas que a ferramenta pode nos entregar com uma configuração mínima. Pesquisando rapidamente na página de plugins do Gatsby encontrei um que parece ser promissor, [veja aqui](https://www.gatsbyjs.com/plugins/gatsby-plugin-google-gtag/).

**Comment by adrcav** [comment]
opa! consigo puxar essa bronca 😁
