### ISSUE TITLE
[Feature] Discord link

### ISSUE THREAD

**Issue by ItaloSa** [ufrpe-devs/ufrpe-devs.github.io#24]
## Opa, qual a bronca?

Hoje usamos um link direto para o invite do Discord. Isso dificulta a divulgação pois é necessário procurar um link em algum material anterior ou mesmo gerar um novo. A ideia do link fixo é usar em nossas comunicações um link padronizado. 

Precisamos então criar uma nova página em `/discord`.  Esta página deve ser feita em cima do layout no [figma](https://www.figma.com/file/HY81qUZGNiUB5YBRoa5UZj/ufrpe-devs-team-library?node-id=458%3A196). O número de online deve vir desse [endpoint](https://discord.com/api/guilds/678334713919832100/widget.json).

![image](https://user-images.githubusercontent.com/28374391/136309908-c41d1240-d345-4a1f-ae44-58298497f3a8.png)

**Comment by brunohgv** [comment]
Pull request pronto para review:
https://github.com/ufrpe-devs/ufrpe-devs.github.io/pull/25
