### ISSUE TITLE
[Feature] Tokens

### ISSUE THREAD

**Issue by ItaloSa** [ufrpe-devs/ufrpe-devs.github.io#6]
Precisamos configurar o tema na lib de UI. Pra isso, é necessário configurar os tokens de acordo com nossas cores e passar para o tema do chakra ui.

**Comment by ThalesGabriel** [comment]
Vou ler a documentação hoje, daí se for semelhante ao material ui eu faço na mesma branch do hero, daí já vai tudo junto

**Comment by ThalesGabriel** [comment]
Fechei sem querer
